### ISSUE TITLE
error: Query sequence with mash_screen 

### ISSUE THREAD

**Issue by mengqiyue** [CCB-SB/plsdbapi#1]
In Linux, a Python script was invoked, and upon executing the command, it displayed the following message: "Http response is not OK. Response status code is 502."
<img width="633" alt="e9b4fecdd6deb9b7e8b5f0d4c77538b" src="https://github.com/CCB-SB/plsdbapi/assets/102716075/6d900728-5052-4de1-81d7-894ffb25267b">

I would really appreciate if you could explain me what's going on here.

Thanks a lot!

**Comment by G-Molano-LA** [comment]
Hi,

Sorry for the late response. Are you still running this issue with the new plsdb version?

Bests,

Alejandra
