### ISSUE TITLE
i wonder how long does it take for the web server to be fully maintained?

### ISSUE THREAD

**Issue by a-piece-of-teemo** [CCB-SB/plsdbapi#2]
i wonder how long does it take for the web server to be fully maintained?

**Comment by G-Molano-LA** [comment]
Hi, 

Thanks for your interest. We will be back very soon, today or tomorrow at the lastest. New sequences are being added. Thanks for your patience.

Best regards,

Alejandra

**Comment by a-piece-of-teemo** [comment]
Thank you for your reply

**Comment by G-Molano-LA** [comment]
> Thank you for your reply

Hi! The webserver is available again now.

Bests,

Alejandra

**Comment by a-piece-of-teemo** [comment]
![image](https://github.com/CCB-SB/plsdbapi/assets/113283540/6104d25a-d5d9-426c-9529-4998b2199db3)
I wonder why I am unable to access this website

**Comment by G-Molano-LA** [comment]
Hi,

You should clear cookies and data site to visualize the website.

Bests,

Alejandra
