### ISSUE TITLE
I wonder if this dataset still needs to undergo preprocessing steps such as quality control, redundancy removal, and pruning?

### ISSUE THREAD

**Issue by a-piece-of-teemo** [CCB-SB/plsdbapi#3]
I wonder if this dataset still needs to undergo preprocessing steps such as quality control, redundancy removal, and pruning?

**Comment by G-Molano-LA** [comment]
Hi,

You can find the details of the preprocessing steps, including redundancy removal, in our publications:

- [PLSDB: a resource of complete bacterial plasmids](https://pubmed.ncbi.nlm.nih.gov/30380090/)
- [PLSDB: advancing a comprehensive database of bacterial plasmids](https://pubmed.ncbi.nlm.nih.gov/34850116/)
